### PR TITLE
Adds hook that runs after all hardware except for the Z drive has been moved in postion.

### PR DESCRIPTION
**Pull request by nicost**
This hook enables autofocussing.  Also fixes an issue where events where not sequences if a 1D drive had been added to stage positions.  Improved some error reporting, and bumped version to 0.37.0.

### CODE REVIEW

**Comment by henrypinkard** [comment]
2 things:

1. You can changed the numbers of the hooks if you want as described in other issue
2. If you're adding a new notification, you need to add the same to the [python side](https://github.com/henrypinkard/pycro-manager/blob/94c3c4c0dafde679f727480f0f4e8bc4e82df1d7/pycromanager/acquisition/acq_eng_py/main/acq_notification.py#L14) so that it knows how to interpret it. I'm hoping to relatively soon write tests for the notification system so that these things behave as expected and its easy to detect errors

**Comment by nicost** [comment]
1. Done.
2. I tried setting up the pycromanager development environmnet, but quickly got lost in Python dependency problems and IDE setup issues.  Do you mind adding these few lines, as I do not have any need for pycromanager other than adding these tests?

**Comment by nicost** [comment]
All right, I am completely confused by the Python side.  There is a complete copy there of AcqEngJ that needs to be modified the same way?  I opened a PR, but I have no way of testing (or even compiling and running that code).

**Comment by henrypinkard** [comment]
Thanks! To clarify, I only meant that one line adding the type of notification, not full functionality in AcqEngPy. 

A little more explanation: Both micro-manager and pycro-manager depend on AcqEngJ. Thus, we don't want changes to AcqEngJ merging without pycro-manager testing them. For this reason, updates to AcqEngJ's version automatically propagate to pycro-manager through Github actions, where they are tested, and then to micro-manager, where they are tested once again.

You should not, in the future, circumvent this system and manually update the AcqEngJ version in ivy.xml as you did in https://github.com/micro-manager/micro-manager/pull/1922, because this has the potential to break pycro-manager. This would have been avoided had the updates been automatic, since the automatic testing system caught the [error](https://github.com/micro-manager/pycro-manager/actions/runs/8676974077/job/23792034243), thus preventing the version update of AcqEngJ from automatically propagating through pycro-manager into MMStudio (https://github.com/micro-manager/pycro-manager/pull/759). 


> 2\. If you're adding a new notification, you need to add the same to the [python side](https://github.com/henrypinkard/pycro-manager/blob/94c3c4c0dafde679f727480f0f4e8bc4e82df1d7/pycromanager/acquisition/acq_eng_py/main/acq_notification.py#L14) so that it knows how to interpret it.

What I was suggesting here was a change pre-emptively fix the problem that would arise, which is that pycro-manager doesn't know how to interpret the new notification type. I believe this is just one or two lines of code, not a full suite of changes to bring AcqEngPy up to parity. 

I will look into fix for this

**Comment by nicost** [comment]
Sorry for creating chaos!  I literally tried to follow what you told me to do including: "I think you could manually change the version number needed of AcqEngJ in ivy".  I still do not understand the complete build system, with multiple dependencies, so your help getting this right is highly appreciated.

**Comment by henrypinkard** [comment]
No problem, its a complicated system that's hard to describe in quick messages. We can go over it at the next developer meeting. For now, good rule of thumb is: let the ivy file get auto updated with acq eng versions

**Pull request merged**
